name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: rustfmt check
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: clippy (deny warnings)
        run: cargo clippy --workspace --all-targets -- -D warnings

  build:
    runs-on: ubuntu-latest
    needs: [fmt, clippy]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build (workspace)
        run: cargo build --workspace --all-targets --locked

  test-default:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Test (workspace, default features)
        run: cargo test --workspace --all-targets --locked --quiet

  test-features:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        features: ["", "debug-api", "bus-metrics", "debug-api,bus-metrics"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Test features (${{ matrix.features || 'default' }})
        shell: bash
        run: |
          if [ -z "${{ matrix.features }}" ]; then
            cargo test -p mmg-microbus --tests --locked --quiet
          else
            cargo test -p mmg-microbus --tests --features "${{ matrix.features }}" --locked --quiet
          fi

